name: audioplayers
description: A Flutter plugin to play multiple audio files simultaneously
version: 5.2.1
homepage: https://github.com/bluefireteam/audioplayers
repository: https://github.com/bluefireteam/audioplayers/tree/master/packages/audioplayers

flutter:
  plugin:
    platforms:
      android:
        default_package: audioplayers_android_exo
      ios:
        default_package: audioplayers_darwin
      linux:
        default_package: audioplayers_linux
      macos:
        default_package: audioplayers_darwin
      web:
        default_package: audioplayers_web
      windows:
        default_package: audioplayers_windows

dependencies:
  audioplayers_android_exo:
    path: ../../packages/audioplayers_android_exo
  #audioplayers_android: ^4.0.3
  audioplayers_darwin:
    path: ../../packages/audioplayers_darwin
  audioplayers_linux:
    path: ../../packages/audioplayers_linux
  audioplayers_platform_interface:
    path: ../../packages/audioplayers_platform_interface
  audioplayers_web:
    path: ../../packages/audioplayers_web
  audioplayers_windows:
    path: ../../packages/audioplayers_windows
  file: '>=6.1.0 <8.0.0'
  flutter:
    sdk: flutter
  http: '>=0.13.1 <2.0.0'
  meta: ^1.7.0
  path_provider: ^2.0.12
  synchronized: ^3.0.0
  uuid: '>=3.0.7 <5.0.0'

dev_dependencies:
  flame_lint: ^1.0.0
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'
